# Generated by Django 4.0.6 on 2023-03-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0003_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
