# Generated by Django 4.0.6 on 2023-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0003_remove_post_subtitle_post_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='no short description available', max_length=100)),
                ('lab_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('lab_details', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('Faculty', 'Faculty'), ('Staff', 'Staff')], max_length=10, null=True),
        ),
    ]
