# Generated by Django 4.0.6 on 2023-04-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0004_labs_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labs',
            new_name='Lab',
        ),
    ]
