# Generated by Django 4.0.6 on 2023-04-12 15:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0005_rename_labs_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=ckeditor.fields.RichTextField(default='no short description available', null=True),
        ),
    ]
