# Generated by Django 4.0.6 on 2023-04-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0007_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
