# Generated by Django 4.0.6 on 2023-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0009_alter_customuser_company_alter_customuser_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
