# Generated by Django 4.0.6 on 2023-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0010_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
