# Generated by Django 4.0.6 on 2023-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ele', '0012_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
